// This file has been auto generated.
package day07

fun main() {
    // To solve part 2, run part 1, assign result to `b` and rerun.
    val b = 1674
    val v = b shr 1
    val d = b shr 2
    val f = b shr 5
    val e = b shr 3
    val g = e or f
    val h = e and f
    val i = h.inv()
    val j = g and i
    val l = d and j
    val m = l.inv()
    val k = d or j
    val n = k and m
    val p = b and n
    val q = p.inv()
    val o = b or n
    val r = o and q
    val s = 1 and r
    val w = s shl 15
    val x = v or w
    val y = x shr 2
    val z = x shr 3
    val aa = x shr 5
    val ab = z or aa
    val ac = z and aa
    val ad = ac.inv()
    val ae = ab and ad
    val af = y or ae
    val ag = y and ae
    val ah = ag.inv()
    val ai = af and ah
    val aj = x or ai
    val ak = x and ai
    val al = ak.inv()
    val am = aj and al
    val an = 1 and am
    val ar = an shl 15
    val aq = x shr 1
    val as_ = aq or ar
    val av = as_ shr 5
    val au = as_ shr 3
    val ax = au and av
    val ay = ax.inv()
    val aw = au or av
    val az = aw and ay
    val at = as_ shr 2
    val bb = at and az
    val bc = bb.inv()
    val ba = at or az
    val bd = ba and bc
    val bf = as_ and bd
    val bg = bf.inv()
    val be = as_ or bd
    val bh = be and bg
    val bi = 1 and bh
    val bm = bi shl 15
    val bl = as_ shr 1
    val bn = bl or bm
    val bo = bn shr 2
    val cg = bn shr 1
    val bp = bn shr 3
    val bq = bn shr 5
    val bs = bp and bq
    val bt = bs.inv()
    val br = bp or bq
    val bu = br and bt
    val bw = bo and bu
    val bx = bw.inv()
    val bv = bo or bu
    val by = bv and bx
    val bz = bn or by
    val ca = bn and by
    val cb = ca.inv()
    val cc = bz and cb
    val cd = 1 and cc
    val ch = cd shl 15
    val ci = cg or ch
    val db = ci shr 1
    val cj = ci shr 2
    val ck = ci shr 3
    val cl = ci shr 5
    val cn = ck and cl
    val co = cn.inv()
    val cm = ck or cl
    val cp = cm and co
    val cq = cj or cp
    val cr = cj and cp
    val cs = cr.inv()
    val ct = cq and cs
    val cu = ci or ct
    val cv = ci and ct
    val cw = cv.inv()
    val cx = cu and cw
    val cy = 1 and cx
    val dc = cy shl 15
    val dd = db or dc
    val df = dd shr 3
    val dg = dd shr 5
    val di = df and dg
    val dj = di.inv()
    val dh = df or dg
    val dk = dh and dj
    val de = dd shr 2
    val dm = de and dk
    val dn = dm.inv()
    val dl = de or dk
    val do_ = dl and dn
    val dp = dd or do_
    val dq = dd and do_
    val dr = dq.inv()
    val ds = dp and dr
    val dt = 1 and ds
    val dx = dt shl 15
    val dw = dd shr 1
    val dy = dw or dx
    val er = dy shr 1
    val ea = dy shr 3
    val eb = dy shr 5
    val ec = ea or eb
    val ed = ea and eb
    val ee = ed.inv()
    val ef = ec and ee
    val dz = dy shr 2
    val eg = dz or ef
    val eh = dz and ef
    val ei = eh.inv()
    val ej = eg and ei
    val ek = dy or ej
    val el = dy and ej
    val em = el.inv()
    val en = ek and em
    val eo = 1 and en
    val es = eo shl 15
    val et = er or es
    val fm = et shr 1
    val ew = et shr 5
    val ev = et shr 3
    val ey = ev and ew
    val ez = ey.inv()
    val ex = ev or ew
    val fa = ex and ez
    val eu = et shr 2
    val fb = eu or fa
    val fc = eu and fa
    val fd = fc.inv()
    val fe = fb and fd
    val ff = et or fe
    val fg = et and fe
    val fh = fg.inv()
    val fi = ff and fh
    val fj = 1 and fi
    val fn = fj shl 15
    val fo = fm or fn
    val gh = fo shr 1
    val fq = fo shr 3
    val fr = fo shr 5
    val ft = fq and fr
    val fu = ft.inv()
    val fs = fq or fr
    val fv = fs and fu
    val fp = fo shr 2
    val fw = fp or fv
    val fx = fp and fv
    val fy = fx.inv()
    val fz = fw and fy
    val ga = fo or fz
    val gb = fo and fz
    val gc = gb.inv()
    val gd = ga and gc
    val ge = 1 and gd
    val gi = ge shl 15
    val gj = gh or gi
    val hc = gj shr 1
    val gl = gj shr 3
    val gm = gj shr 5
    val go = gl and gm
    val gp = go.inv()
    val gn = gl or gm
    val gq = gn and gp
    val gk = gj shr 2
    val gs = gk and gq
    val gt = gs.inv()
    val gr = gk or gq
    val gu = gr and gt
    val gv = gj or gu
    val gw = gj and gu
    val gx = gw.inv()
    val gy = gv and gx
    val gz = 1 and gy
    val hd = gz shl 15
    val he = hc or hd
    val hx = he shr 1
    val hf = he shr 2
    val hh = he shr 5
    val hg = he shr 3
    val hi = hg or hh
    val hj = hg and hh
    val hk = hj.inv()
    val hl = hi and hk
    val hm = hf or hl
    val hn = hf and hl
    val ho = hn.inv()
    val hp = hm and ho
    val hr = he and hp
    val hs = hr.inv()
    val hq = he or hp
    val ht = hq and hs
    val hu = 1 and ht
    val hy = hu shl 15
    val hz = hx or hy
    val ib = hz shr 3
    val ic = hz shr 5
    val id = ib or ic
    val ie = ib and ic
    val if_ = ie.inv()
    val ig = id and if_
    val ia = hz shr 2
    val ii = ia and ig
    val ij = ii.inv()
    val ih = ia or ig
    val ik = ih and ij
    val il = hz or ik
    val im = hz and ik
    val in_ = im.inv()
    val io = il and in_
    val ip = 1 and io
    val it = ip shl 15
    val is_ = hz shr 1
    val iu = is_ or it
    val jn = iu shr 1
    val iv = iu shr 2
    val iw = iu shr 3
    val ix = iu shr 5
    val iy = iw or ix
    val iz = iw and ix
    val ja = iz.inv()
    val jb = iy and ja
    val jd = iv and jb
    val je = jd.inv()
    val jc = iv or jb
    val jf = jc and je
    val jh = iu and jf
    val ji = jh.inv()
    val jg = iu or jf
    val jj = jg and ji
    val jk = 1 and jj
    val jo = jk shl 15
    val jp = jn or jo
    val jq = jp shr 2
    val jr = jp shr 3
    val js = jp shr 5
    val jt = jr or js
    val ju = jr and js
    val jv = ju.inv()
    val jw = jt and jv
    val jx = jq or jw
    val jy = jq and jw
    val jz = jy.inv()
    val ka = jx and jz
    val kb = jp or ka
    val kc = jp and ka
    val kd = kc.inv()
    val ke = kb and kd
    val kf = 1 and ke
    val kj = kf shl 15
    val ki = jp shr 1
    val kk = ki or kj
    val ld = kk shr 1
    val kl = kk shr 2
    val km = kk shr 3
    val kn = kk shr 5
    val ko = km or kn
    val kp = km and kn
    val kq = kp.inv()
    val kr = ko and kq
    val ks = kl or kr
    val kt = kl and kr
    val ku = kt.inv()
    val kv = ks and ku
    val kw = kk or kv
    val kx = kk and kv
    val ky = kx.inv()
    val kz = kw and ky
    val la = 1 and kz
    val le = la shl 15
    val lf = ld or le
    val ly = lf shr 1
    val c = 0
    val t = c shl 1
    val u = t or s
    val ao = u shl 1
    val ap = ao or an
    val bj = ap shl 1
    val bk = bj or bi
    val ce = bk shl 1
    val cf = ce or cd
    val cz = cf shl 1
    val da = cz or cy
    val du = da shl 1
    val dv = du or dt
    val ep = dv shl 1
    val eq = ep or eo
    val fk = eq shl 1
    val fl = fk or fj
    val gf = fl shl 1
    val gg = gf or ge
    val ha = gg shl 1
    val hb = ha or gz
    val hv = hb shl 1
    val hw = hv or hu
    val iq = hw shl 1
    val ir = iq or ip
    val jl = ir shl 1
    val jm = jl or jk
    val kg = jm shl 1
    val kh = kg or kf
    val lb = kh shl 1
    val lc = lb or la
    val lw = lc shl 1
    val lh = lf shr 3
    val li = lf shr 5
    val lk = lh and li
    val ll = lk.inv()
    val lj = lh or li
    val lm = lj and ll
    val lg = lf shr 2
    val lo = lg and lm
    val lp = lo.inv()
    val ln = lg or lm
    val lq = ln and lp
    val lr = lf or lq
    val ls = lf and lq
    val lt = ls.inv()
    val lu = lr and lt
    val lv = 1 and lu
    val lx = lw or lv
    val a = lx
    val lz = lv shl 15
    val ma = ly or lz
   println(a)
}
